### ISSUE TITLE
Could we merge this plugin with plugins/emqttd_auth_mysql?

### ISSUE THREAD

**Issue by erylee** [emqtt/emqttd_plugin_mysql#1]
@kimiscircle, Could we merge these two plugins together? And I found this plugin has c_src, could it be compiled successfully on Windows? 

Thanks for your awesome plugin:)

**Comment by kimiscircle** [comment]
Ofcourse, replacement should work

**Comment by lsxredrain** [comment]
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8' at line 8
fix bug as follows：
CREATE TABLE `auth_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `password` varchar(128) NOT NULL,
  `is_superuser` tinyint(1) NOT NULL,
  `username` varchar(30) NOT NULL,
  PRIMARY KEY (`id`)
  UNIQUE KEY `username` (`username`),
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8
CREATE TABLE `auth_acl` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `topic` varchar(100) NOT NULL,
  `username` varchar(30) NOT NULL,
  `rw` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8

**Comment by kimiscircle** [comment]
@lsxredrain , ok, updated

**Comment by lsxredrain** [comment]
[
{emysql, [
    {pool, 4},
        {host, "localhost"},
        {port, 3306},
        {username, "root"},
        {password, "root"},
        {database, "emqtt"},
        {encoding, utf8}
]},
{emqttd_plugin_mysql, [
    {users_table, auth_user},  %% here "users_table" should modified "to user_table" 
    {acls_table, auth_acl},
    {field_mapper, [
        {username, username},
        {password, password, pbkdf2},
        {user_super, is_super_user},
        {acl_username, username},
        {acl_rw, rw},
        {acl_topic, topic}
    ]}
]}
].

**Comment by kimiscircle** [comment]
@lsxredrain  updated
