### ISSUE TITLE
How to create user/password in mqtt_user table when I use emqttd_plugin_mysql

### ISSUE THREAD

**Issue by chenek** [emqtt/emqttd_plugin_mysql#10]
I have enable emqttd_plugin_mysql. Does anyone know how to create user/password with SHA256 in mqtt_user table when I use emqttd_plugin_mysql?

**Comment by chenek** [comment]
I can use MD5 and SHA now. Will try to find a way to use SHA256 later

**Comment by erylee** [comment]
:) well done.
