### ISSUE TITLE
MySQL connection appears to be closed

### ISSUE THREAD

**Issue by josephduchesne** [emqtt/emqttd_plugin_mysql#15]
I am getting an intermittent error that I think may be related to the mysql connection timing out. Mysql is set to a 5 minute connection timeout.

`Username 'login_test' login failed for {{{badmatch,{error,closed}},[{mysql_protocol,prepare,3,[{file,"src/mysql_protocol.erl"},{line,98}]},{mysql,handle_call,3,[{file,"src/mysql.erl"},{line,585}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{gen_server,call,[<0.24751.0>,{param_query,"select is_superuser from mqtt_user where username = ? limit 1",[<<"login_test">>]},infinity]}}`

**Comment by emqplus** [comment]
Hi @josephduchesne, the root cause is https://github.com/mysql-otp/mysql-otp/issues/33

Please configure emqttd_plugin_mysql/etc/plugin.config for a quick fix:

```
   {mysql_pool, [
        %% ecpool options
        {pool_size, 8},
        {auto_reconnect, 1},

        %% mysql options
        {host,     "localhost"},
        {port,     3306},
        {user,     ""},
        {password, ""},
        {database, "mqtt"},
        {encoding, utf8},
        {keep_alive, 60000}
    ]},
```

**Comment by emqplus** [comment]
@josephduchesne, The mysql driver has been upgraded to 1.2.0. Please pull the last master branch of emqttd project.
