### ISSUE TITLE
plugins.config have a bug,mqtt_users should be auth_user

### ISSUE THREAD

**Issue by lsxredrain** [emqtt/emqttd_plugin_mysql#3]
[
  {emysql, [
    {pool,      4},
    {host,      "localhost"},
    {port,      3306},
    {username,  "root"},
    {password,  "public"},
    {database,  "mqtt"},
    {encoding,  utf8}
  ]},
  {emqttd_plugin_mysql, [
    {user_table, mqtt_users},  ------ >>> change to auth_user
    %% plain, md5, sha
    {password_hash, plain},
    {field_mapper, [
       {username, username},
       {password, password}
    ]}
  ]}
].

**Comment by erylee** [comment]
@lsxredrain, this plugin has been rewrited. And I put your version to 'pbkdf2' branch, for users cannot build c_src/ on Windows. 

Could you try the pure erlang pbkdf2 library: https://github.com/basho/erlang-pbkdf2.git?
