### ISSUE TITLE
emqttd_plugin_mysql load error on emqttd-ubuntu64-0.15.0-beta-20160131

### ISSUE THREAD

**Issue by chenek** [emqtt/emqttd_plugin_mysql#9]
I tried to use emqttd_plugin_mysql load error on emqttd-ubuntu64-0.15.0-beta-20160131 but I get the following error. Can anyone help?

./bin/emqttd_ctl plugins load emqttd_plugin_mysql
load plugin error: {emqttd_plugin_mysql,
                       {bad_return,
                           {{emqttd_plugin_mysql,start,[normal,[]]},
                            {'EXIT',
                                {{badmatch,{error,existed}},
                                 [{emqttd_plugin_mysql,start,2,
                                      [{file,"src/emqttd_plugin_mysql.erl"},
                                       {line,45}]},
                                  {application_master,start_it_old,4,
                                      [{file,"application_master.erl"},
                                       {line,273}]}]}}}}}

**Comment by erylee** [comment]
It seems the mysql plugin has been loaded:

1. ./bin/emqttd_ctl plugins list
2. grep crasher logs/emqttd_sasl.log

**Comment by chenek** [comment]
Actually, when I load plugin first time, I get the following error.

./bin/emqttd_ctl plugins load emqttd_plugin_mysql
load plugin error: {emqttd_plugin_mysql,
                    {{shutdown,
                      {failed_to_start_child,mysql_pool,
                       {shutdown,
                        {failed_to_start_child,worker_sup,
                         {shutdown,
                          {failed_to_start_child,
                           {worker,1},
                           {1045,<<"28000">>,
                            <<"Access denied for user ''@'127.0.0.1' (using password: YES)">>}}}}}}},
                     {emqttd_plugin_mysql,start,[normal,[]]}}}


If I issue ./bin/emqttd_ctl plugins list, I get the following results:

Plugin(emqttd_dashboard, version=0.15.0, description=emqttd web dashboard, active=true)
Plugin(emqttd_plugin_mysql, version=0.15.0, description=emqttd Authentication/ACL with MySQL, active=false)
Plugin(emqttd_plugin_pgsql, version=0.15.0, description=emqttd PostgreSQL Plugin, active=false)
Plugin(emqttd_plugin_redis, version=0.15, description=emqttd Redis Plugin, active=false)
Plugin(emqttd_plugin_template, version=0.15.0, description=emqttd plugin template, active=false)
Plugin(emqttd_recon, version=0.14, description=emqttd recon plugin, active=false)
Plugin(emqttd_stomp, version=0.15.0, description=Stomp Protocol Plugin for emqttd broker, active=false)

If I do "grep crasher logs/emqttd_sasl.log", I get the following results.
grep: logs/emqttd_sasl.log: No such file or directory

I have the following settings in my plugin.config

[

{emqttd_plugin_mysql, [

    {mysql_pool, [
        %% ecpool options
        {pool_size, 4},
        {pool_type, round_robin},
        {auto_reconnect, 3},

        %% mysql options
        {host,     "localhost"},
        {port,     3306},
        {user,     "root"},
        {password, "12345678"},
        {database, "mqtt"},
        {encoding, utf8}
    ]},

    %% select password only
    {authquery, "select password from mqtt_user where username = '%u' limit 1"},

    %% hash algorithm: md5, sha, sha256, pbkdf2?
    {password_hash, sha256},

    %% select password with salt
    %% {authquery, "select password, salt from mqtt_user where username = '%u'"},

    %% sha256 with salt prefix
    %% {password_hash, {salt, sha256}},

    %% sha256 with salt suffix
    %% {password_hash, {sha256, salt}},

    %% comment this query, the acl will be disabled
    {aclquery, "select * from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'"},

    %% If no rules matched, return...
    {acl_nomatch, allow}
]}
].

What do I do wrong?

Thanks for your help.

**Comment by erylee** [comment]
Username or password error?
```
{1045,<<"28000">>,
<<"Access denied for user ''@'127.0.0.1' (using password: YES)">>}}}}}}},
{emqttd_plugin_mysql,start,[normal,[]]}}}
```

**Comment by chenek** [comment]
I am sure I give correct user and password for MySQL connection. Why does it show "''@'127.0.0.1'" which doesn't have user in it?

**Comment by chenek** [comment]
I find out where the problem is. I create a plugin.config in emqttd/etc which is incorrect. I should use the one under emqttd/plugins/emqttd_plugin_mysql/etc. 

Thanks for your help.
